### ISSUE TITLE
Kanban Board: Recipe app

### ISSUE THREAD

**Issue by shubhambhoyar077** [shubhambhoyar077/recipe-app#12]
## Highlights

- The following people are assigned to each task.

- @shubhambhoyar077 : **Team Member 1**.
- @edubew  : **Team Member 2**.

**[Github Project Link](https://github.com/users/shubhambhoyar077/projects/5)**

### Note: We are two in a team.

**Comment by Abenezer-Tilahun** [comment]
Hi @shubhambhoyar077 @edubew 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻



✔️ Good job for provide the information  about the number of people in their group
✔️ Good Job for provide link to their GitHub project
✔️ Good job for implementing RoR group project: set up your Kanban board  

## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Comment by shubhambhoyar077** [comment]
Hi @Abenezer-Tilahun ,
Thanks for Approval. :smile:
